### PR TITLE
Added support for storing the admin port in the `InstanceMetadata`

### LINKED ISSUE #10: add admin port to InstanceMetadata and publish in CuratorAdvertiser
In distributed environments, being able to allocate ports dynamically (via setting the port to 0 in the config) on hosts for various service instances is valuable -- as it avoids having to manually resolve conflicts in configuration management.

This works great already in dropwizard-discovery. However, the admin port is not included in the `InstanceMetadata`, and thus conflicts can still occur when service instances are spun up.

### PR DESCRIPTION
**Pull request by jplock**
I made the `adminPort` Optional because the Dropwizard simple server doesn't expose and admin port, only the listen port.  The Dropwizard default server exposes both.

Fixes #10

### CODE REVIEW

**Comment by stantonk** [comment]
@jplock sorry it took me so long! I built a demo project tonight, and I'm getting an error. I have a suspicion that for some reason, the code is trying to create `/dropwizard` twice in Zookeeper, and the 2nd attempt fails because it already exists.

`org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dropwizard
`

```
INFO  [2015-12-08 05:32:43,876] org.eclipse.jetty.util.log: Logging initialized @1830ms
INFO  [2015-12-08 05:32:44,019] org.apache.curator.framework.imps.CuratorFrameworkImpl: Starting
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:host.name=10.0.1.101
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:java.version=1.8.0_65
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
...
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:os.name=Mac OS X
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:os.arch=x86_64
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:os.version=10.11.1
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:user.name=stantonk
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:user.home=/Users/stantonk
INFO  [2015-12-08 05:32:44,030] org.apache.zookeeper.ZooKeeper: Client environment:user.dir=/Users/stantonk/Documents/code/others/dzdiscohw
INFO  [2015-12-08 05:32:44,031] org.apache.zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=org.apache.curator.ConnectionState@132ddbab
INFO  [2015-12-08 05:32:44,051] org.apache.zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
INFO  [2015-12-08 05:32:44,073] io.dropwizard.server.ServerFactory: Starting HelloWorldService
INFO  [2015-12-08 05:32:44,127] org.apache.zookeeper.ClientCnxn: Socket connection established to localhost/127.0.0.1:2181, initiating session
INFO  [2015-12-08 05:32:44,151] org.eclipse.jetty.setuid.SetUIDListener: Opened application@64da2a7{HTTP/1.1}{0.0.0.0:56914}
INFO  [2015-12-08 05:32:44,151] org.eclipse.jetty.setuid.SetUIDListener: Opened admin@46074492{HTTP/1.1}{0.0.0.0:56915}
INFO  [2015-12-08 05:32:44,154] org.eclipse.jetty.server.Server: jetty-9.2.9.v20150224
INFO  [2015-12-08 05:32:44,275] org.apache.zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x15180139fa10000, negotiated timeout = 6000
INFO  [2015-12-08 05:32:44,279] org.apache.curator.framework.state.ConnectionStateManager: State change: CONNECTED
WARN  [2015-12-08 05:32:44,320] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED io.dropwizard.discovery.manage.CuratorManager@1df98368: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dropwizard
! org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dropwizard
! at org.apache.zookeeper.KeeperException.create(KeeperException.java:119) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
! at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
! at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
! at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:720) ~[curator-framework-2.9.1.jar:na]
! at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:703) ~[curator-framework-2.9.1.jar:na]
! at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[curator-client-2.9.1.jar:na]
! at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:699) ~[curator-framework-2.9.1.jar:na]
! at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:477) ~[curator-framework-2.9.1.jar:na]
! at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:467) ~[curator-framework-2.9.1.jar:na]
! at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:447) ~[curator-framework-2.9.1.jar:na]
! at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:355) ~[curator-framework-2.9.1.jar:na]
! at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:291) ~[curator-framework-2.9.1.jar:na]
! at io.dropwizard.discovery.manage.CuratorManager.start(CuratorManager.java:32) ~[dropwizard-discovery-0.9.1-2-SNAPSHOT.jar:0.9.1-2-SNAPSHOT]
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27) ~[dropwizard-lifecycle-0.8.1.jar:0.8.1]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.Server.start(Server.java:387) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.Server.doStart(Server.java:354) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.Application.run(Application.java:73) [dropwizard-core-0.8.1.jar:0.8.1]
! at com.github.stantonk.dz.discovery.helloworld.dzdiscohw.HelloWorldService.main(HelloWorldService.java:40) [classes/:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
! at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
INFO  [2015-12-08 05:32:44,326] org.eclipse.jetty.server.ServerConnector: Started application@64da2a7{HTTP/1.1}{0.0.0.0:56914}
WARN  [2015-12-08 05:32:44,327] org.eclipse.jetty.util.thread.QueuedThreadPool: dw-admin{STOPPED,1<=0<=64,i=0,q=0} rejected org.eclipse.jetty.util.thread.NonBlockingThread@5aa0dbf4
WARN  [2015-12-08 05:32:44,327] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED org.eclipse.jetty.server.ServerConnector$ServerConnectorManager@16afbd92: java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.util.thread.NonBlockingThread@5aa0dbf4
! java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.util.thread.NonBlockingThread@5aa0dbf4
! at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:362) ~[jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:160) ~[jetty-io-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:258) ~[jetty-io-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.Server.doStart(Server.java:366) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.Application.run(Application.java:73) [dropwizard-core-0.8.1.jar:0.8.1]
! at com.github.stantonk.dz.discovery.helloworld.dzdiscohw.HelloWorldService.main(HelloWorldService.java:40) [classes/:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
! at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
WARN  [2015-12-08 05:32:44,328] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED admin@46074492{HTTP/1.1}{0.0.0.0:56915}: java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.util.thread.NonBlockingThread@5aa0dbf4
! java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.util.thread.NonBlockingThread@5aa0dbf4
! at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:362) ~[jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:160) ~[jetty-io-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:258) ~[jetty-io-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) ~[jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106) ~[jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.Server.doStart(Server.java:366) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.Application.run(Application.java:73) [dropwizard-core-0.8.1.jar:0.8.1]
! at com.github.stantonk.dz.discovery.helloworld.dzdiscohw.HelloWorldService.main(HelloWorldService.java:40) [classes/:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
! at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
WARN  [2015-12-08 05:32:44,328] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED org.eclipse.jetty.server.Server@2c5d601e: MultiException[org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dropwizard, java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.util.thread.NonBlockingThread@5aa0dbf4]
! org.eclipse.jetty.util.MultiException: Multiple exceptions
! at org.eclipse.jetty.server.Server.doStart(Server.java:329) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.Application.run(Application.java:73) [dropwizard-core-0.8.1.jar:0.8.1]
! at com.github.stantonk.dz.discovery.helloworld.dzdiscohw.HelloWorldService.main(HelloWorldService.java:40) [classes/:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
! at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
ERROR [2015-12-08 05:32:44,328] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! org.eclipse.jetty.util.MultiException: Multiple exceptions
! at org.eclipse.jetty.server.Server.doStart(Server.java:329) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) ~[dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.8.1.jar:0.8.1]
! at io.dropwizard.Application.run(Application.java:73) [dropwizard-core-0.8.1.jar:0.8.1]
! at com.github.stantonk.dz.discovery.helloworld.dzdiscohw.HelloWorldService.main(HelloWorldService.java:40) [classes/:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
! at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
INFO  [2015-12-08 05:32:44,335] org.eclipse.jetty.server.ServerConnector: Stopped application@64da2a7{HTTP/1.1}{0.0.0.0:0}
INFO  [2015-12-08 05:32:44,335] org.eclipse.jetty.server.ServerConnector: Stopped admin@46074492{HTTP/1.1}{0.0.0.0:0}
Exception in thread "main" MultiException[org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dropwizard, java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.util.thread.NonBlockingThread@5aa0dbf4]
	at org.eclipse.jetty.server.Server.doStart(Server.java:329)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:73)
	at com.github.stantonk.dz.discovery.helloworld.dzdiscohw.HelloWorldService.main(HelloWorldService.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dropwizard
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:720)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:703)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:699)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:477)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:467)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:447)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:355)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:291)
	at io.dropwizard.discovery.manage.CuratorManager.start(CuratorManager.java:32)
	at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:73)
	at com.github.stantonk.dz.discovery.helloworld.dzdiscohw.HelloWorldService.main(HelloWorldService.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.util.thread.NonBlockingThread@5aa0dbf4
	at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:362)
	at org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:160)
	at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:258)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:73)
	at com.github.stantonk.dz.discovery.helloworld.dzdiscohw.HelloWorldService.main(HelloWorldService.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1
```

**Comment by stantonk** [comment]
@jplock here's my demo project https://github.com/stantonk/dzdiscohw

incidentally, i have stuff on dz 0.8.x, is there any reason this change wouldn't be backwards compatible?

**Comment by jplock** [comment]
@stantonk I just pushed up some changes which should hopefully resolve your issue.

**Comment by stantonk** [comment]
I'm now getting this error:

```
INFO  [2016-04-14 15:22:42,595] org.apache.curator.framework.imps.EnsembleTracker: New config event received: null
INFO  [2016-04-14 15:22:42,596] org.eclipse.jetty.server.Server: jetty-9.2.9.v20150224
ERROR [2016-04-14 15:22:42,600] org.apache.curator.framework.imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up
! java.lang.NullPointerException: null
! at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106) ~[na:1.8.0_65]
! at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:163) ~[curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.EnsembleTracker.access$200(EnsembleTracker.java:48) ~[curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:134) ~[curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:829) [curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:611) [curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:151) [curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:210) [curator-framework-3.0.0.jar:na]
! at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:619) [zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007]
! at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:528) [zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007]
```

Looks like it can't talk to zookeeper anymore for some reason...

**Comment by stantonk** [comment]
Yup, looks like Curator 3.x is incompatible with Zookeeper 3.4 :( I would strongly vote for keeping with Curator 2.x, as I suspect many people are on ZK 3.4 and can't upgrade anytime soon.

See http://curator.apache.org/ (at the bottom):

```
The are currently two released versions of Curator, 2.x.x and 3.x.x:

Curator 2.x.x - compatible with both ZooKeeper 3.4.x and ZooKeeper 3.5.x
Curator 3.x.x - compatible only with ZooKeeper 3.5.x and includes support for new features such as dynamic reconfiguration, etc.
```

**Comment by jplock** [comment]
Well that stinks.  Thanks for finding that @stantonk.  I'll revert the curator upgrade and update this PR.

**Comment by jplock** [comment]
@stantonk I pushed another commit which goes back to Curator 2.10.0

**Comment by stantonk** [comment]
@jplock cool!

**Pull request merged**
